var extensions = ['4gh', '4gl', '8th', 'a65', 'aap', 'abap', 'abc', 'abl',
'ace', 'ACE', 'action', 'ad', 'ada', 'adb', 'ado', 'adoc', 'ads', 'afm', 'ahk',
'ai', 'aidl', 'al', 'am', 'aml', 'art', 'as', 'asa', 'asciidoc', 'asm', 'asn',
'asn1', 'asp', 'at', 'atg', 'atl', 'atom', 'au3', 'ave', 'awk', 'bas', 'bash',
'bat', 'bazel', 'bbl', 'bc', 'bdf', 'beancount', 'bi', 'bib', 'bl', 'bsdl',
'bst', 'btm', 'BUILD', 'builder', 'bzl', 'c', 'C', 'cabal', 'cbl', 'cc', 'cdf',
'cdl', 'cdxml', 'cfc', 'cfg', 'cfi', 'cfm', 'ch', 'chai', 'chf', 'cho',
'chopro', 'chordpro', 'chs', 'cjs', 'cl', 'class', 'clj', 'cljc', 'cljs',
'cljx', 'clp', 'cls', 'cm', 'cmake', 'cmd', 'cmod', 'cob', 'com', 'comp',
'con', 'conf', 'cpp', 'cpt', 'cpy', 'crd', 'crdpro', 'crm', 'cs', 'csc',
'csdl', 'csh', 'csp', 'csproj', 'css', 'ctl', 'ctp', 'cu', 'cuh', 'cxx', 'cyn',
'd', 'dart', 'dat', 'db', 'dcd', 'dcl', 'dec', 'decl', 'def', 'DEF', 'desc',
'desktop', 'diff', 'directory', 'do', 'Dockerfile', 'dot', 'dpr', 'drac',
'drc', 'drt', 'ds', 'dsl', 'dsm', 'dsp', 'dtd', 'dtml', 'dts', 'dtsi', 'dtx',
'dylan', 'e', 'E', 'ebuild', 'ec', 'EC', 'ecd', 'eclass', 'ed', 'edf', 'edif',
'edn', 'edo', 'eex', 'el', 'elm', 'eml', 'eni', 'ent', 'env', 'epp', 'eps',
'epsf', 'epsi', 'erb', 'erl', 'errsum', 'es', 'eu', 'EU', 'ev', 'ew', 'EW',
'ex', 'EX', 'exp', 'exs', 'exu', 'EXU', 'exw', 'EXW', 'f', 'F', 'f03', 'F03',
'f08', 'F08', 'f77', 'F77', 'f90', 'F90', 'f95', 'F95', 'factor', 'fal', 'fan',
'fb', 'fdr', 'feature', 'fex', 'fnl', 'focexec', 'for', 'FOR', 'fortran',
'fpc', 'fpp', 'FPP', 'frm', 'frt', 'fs', 'fsl', 'ft', 'fth', 'ftn', 'FTN',
'fwt', 'g', 'gawk', 'gdmo', 'ged', 'gemspec', 'gift', 'git', 'go', 'gp', 'gpi',
'gpr', 'gradle', 'gretl', 'groovy', 'gs', 'gsp', 'gv', 'h', 'H', 'h32', 'haml',
'hb', 'hdl', 'hex', 'hgrc', 'hh', 'hlp', 'hog', 'hook', 'hpp', 'hrl', 'hs',
'hsc', 'hsig', 'hsm', 'ht', 'htb', 'htm', 'html', 'htpp', 'htt', 'hw', 'hws',
'hxx', 'i', 'iba', 'ibi', 'ice', 'icl', 'icn', 'idl', 'ih', 'ihlp', 'ii',
'ijs', 'il', 'ils', 'imata', 'imp', 'inc', 'inf', 'INF', 'ini', 'inl', 'ino',
'inp', 'install', 'intr', 'ipp', 'ipynb', 'isc', 'iss', 'ist', 'it', 'itcl',
'itk', 'j73', 'jacl', 'jal', 'JAL', 'jav', 'java', 'javascript', 'jgr', 'jj',
'jjt', 'jl', 'jov', 'jovial', 'jpl', 'jpr', 'jrexx', 'js', 'json', 'jsonp',
'jsp', 'jsx', 'k', 'key', 'kix', 'ks', 'ksh', 'kt', 'ktm', 'kts', 'kv', 'l',
'L', 'latex', 'latte', 'ld', 'ldif', 'leex', 'less', 'lex', 'lgt', 'lhs',
'lib', 'lid', 'liquid', 'lisp', 'list', 'lite', 'll', 'log', 'lot', 'lotos',
'lou', 'lout', 'lpc', 'lpr', 'lsl', 'lsp', 'lss', 'lst', 'lt', 'lte', 'ltx',
'lua', 'lxx', 'm', 'm2', 'm4', 'm4gl', 'mac', 'mak', 'man', 'map', 'mar',
'markdown', 'mas', 'mason', 'master', 'mat', 'mata', 'mc', 'mch', 'md',
'mdown', 'mdwn', 'me', 'mel', 'menu', 'mf', 'mgl', 'mgp', 'mhtml', 'mi', 'mib',
'mix', 'mixal', 'mjs', 'mk', 'mkd', 'mkdn', 'mkii', 'mkiv', 'mklx', 'mkvi',
'mkxl', 'ml', 'mli', 'mlip', 'mll', 'mlp', 'mlt', 'mly', 'mm', 'mmp', 'mms',
'mo', 'moc', 'mod', 'MOD', 'module', 'mof', 'mom', 'monk', 'moo', 'mot', 'mp',
'mpl', 'ms', 'msc', 'msf', 'msql', 'mst', 'mu', 'mush', 'mv', 'mws', 'my',
'mysql', 'n1ql', 'nanorc', 'nb', 'ncf', 'ninja', 'nqc', 'nql', 'nr', 'NS',
'nse', 'nsh', 'nsi', 'obj', 'occ', 'odl', 'opam', 'or', 'ora', 'orx',
'override', 'p', 'p36', 'p6', 'pac', 'page', 'papp', 'pas', 'patch', 'pbtxt',
'pc', 'pcmk', 'pdb', 'pde', 'pdf', 'permissions', 'pfa', 'php', 'phtml',
'pike', 'pk', 'pkb', 'pkg', 'pks', 'pl', 'PL', 'pl1', 'pld', 'pli', 'plm',
'plp', 'pls', 'plsql', 'plx', 'pm', 'pm6', 'pml', 'pmod', 'po', 'pod', 'pod6',
'pot', 'pov', 'pp', 'ppd', 'pr', 'prg', 'pro', 'properties', 'properties_',
'proto', 'ps', 'ps1', 'ps1xml', 'psc1', 'psd1', 'psf', 'psgi', 'psl', 'psm1',
'pssc', 'pt', 'ptl', 'pxd', 'pxml', 'pxsl', 'py', 'pyi', 'pyw', 'pyx', 'qc',
'quake', 'r', 'R', 'rad', 'rake', 'raku', 'rakudoc', 'rakumod', 'rakutest',
'raml', 'rant', 'rb', 'rbs', 'rbw', 'rc', 'rch', 'rcp', 'rd', 'Rd', 'rdf',
'recipe', 'ref', 'reg', 'rego', 'rej', 'rem', 'remind', 'rex', 'rexx', 'rexxj',
'rhtml', 'rib', 'rjs', 'rkt', 'rmd', 'Rmd', 'rnc', 'rng', 'rnw', 'Rnw',
'rockspec', 'roff', 'rpl', 'rq', 'rrst', 'Rrst', 'rs', 'rss', 'rst', 'rtf',
'ru', 'rul', 'rules', 'run', 'rxj', 'rxml', 'rxo', 's19', 's28', 's37', 's85',
'sa', 'sas', 'sass', 'sba', 'sbt', 'sc', 'scala', 'sce', 'sci', 'scm', 'score',
'scpt', 'scss', 'sd', 'sdc', 'sdl', 'sed', 'sexp', 'sgm', 'sgml', 'sh',
'shtml', 'si', 'sieve', 'sig', 'sil', 'sim', 'sin', 'siv', 'sl', 'slt', 'smcl',
'smd', 'Smd', 'smi', 'smil', 'smith', 'sml', 'smt', 'sno', 'snw', 'Snw', 'sp',
'sparql', 'spd', 'spdata', 'spec', 'speedup', 'spi', 'spice', 'spt', 'spy',
'sqi', 'sql', 'sqlj', 'sqr', 'srec', 'srst', 'Srst', 'ss', 'ssc', 'ssi', 'ssm',
'_sst', 'sst', 'st', 'stm', 'stp', 'strl', 'sty', 'sum', 'sv', 'svelte', 'svg',
'svh', 'swift', 'sys', 't', 't6', 'tak', 'task', 'tcc', 'tcl', 'tcsh', 'tdf',
'testGroup', 'testUnit', 'tex', 'texi', 'texinfo', 'text', 'tf', 'theme', 'ti',
'tk', 'tlh', 'tli', 'tmac', 'tmp', 'tmpl', 'toc', 'toml', 'tpl', 'tpm', 'tpp',
'tr', 'treetop', 'ts', 'tsc', 'tsscl', 'tssgm', 'tssop', 'tsx', 'ttl', 'tutor',
'twig', 'txi', 'txt', 'tyb', 'tyc', 'typ', 'uc', 'ui', 'uil', 'uit', 'ulpc',
'upstream', 'upstreaminstall', 'usserver', 'usw2kagt', 'v', 'va', 'vams', 'vb',
'vba', 'vbe', 'vbs', 'vc', 'vhd', 'vhdl', 'vhdl_', 'vho', 'vim', 'vr', 'vrh',
'vri', 'vroom', 'vst', 'vue', 'w', 'wast', 'wat', 'wbt', 'web', 'webmanifest',
'wiki', 'wm', 'wml', 'wpl', 'wrap', 'wrl', 'wrm', 'ws', 'wsdl', 'wsml', 'x',
'xht', 'xhtml', 'xin', 'xlf', 'xliff', 'xmi', 'xml', 'xom', 'xpm', 'xpm2',
'xq', 'xql', 'xqm', 'xquery', 'xqy', 'xs', 'xsd', 'xsl', 'xslt', 'xul', 'y',
'yaml', 'yaws', 'yml', 'yxx', 'yy', 'z8a', 'zsh', 'zsql', 'zu', 'zut']

module.exports.extensions = extensions;
