var extensions = ['txt', 'inp', '8th', 'aap', 'cfg', 'abap', 'abc', 'abl',
'wrm', 'adb', 'ads', 'ada', 'gpr', 'tdf', 'aidl', 'run', 'ino', 'pde', 'conf',
'com', 'a65', 'scpt', 'am', 'aml', 'art', 'asciidoc', 'adoc', 'asn', 'asn1',
'asa', 'asp', 'lst', 'lst', 'asm', 'mac', 'lst', 'mar', 'atl', 'as', 'atom',
'au3', 'ahk', 'at', 'ave', 'awk', 'gawk', 'mch', 'ref', 'imp', 'bas', 'vb',
'vbs', 'dsm', 'ctl', 'iba', 'ibi', 'fb', 'bi', 'bat', 'sys', 'cmd', 'cmd',
'cmd', 'btm', 'bc', 'bdf', 'beancount', 'bib', 'bst', 'conf', 'conf', 'key',
'db', 'bl', 'bsdl', 'bzl', 'bazel', 'BUILD', 'c', 'lpc', 'ulpc', 'cs', 'csdl',
'cabal', 'toc', 'chai', 'cdl', 'recipe', 'crm', 'cyn', 'cc', 'cpp', 'cxx', 'c',
'hh', 'hxx', 'hpp', 'ipp', 'moc', 'tcc', 'inl', 'C', 'H', 'h', 'chf', 'tlh',
'css', 'cmd', 'con', 'ch', 'chopro', 'crd', 'cho', 'crdpro', 'chordpro', 'dcl',
'icl', 'eni', 'ent', 'prg', 'clj', 'cljs', 'cljx', 'cljc', 'cmake', 'cmake',
'theme', 'theme', 'cbl', 'cob', 'lib', 'cpy', 'atg', 'cfm', 'cfi', 'cfc', 'cu',
'cuh', 'Dockerfile', 'dcd', 'cfg', 'cfg', 'ex', 'exs', 'eex', 'leex', 'eu',
'ew', 'exu', 'exw', 'EU', 'EW', 'EX', 'EXU', 'EXW', 'cfg', 'quake', 'cfg',
'cfg', 'cfg', 'qc', 'cfg', 'feature', 'csp', 'fdr', 'pld', 'si', 'dart', 'drt',
'list', 'desc', 'd', 'desktop', 'directory', 'diff', 'rej', 'patch', 'rul',
'com', 'dot', 'gv', 'lid', 'intr', 'dylan', 'def', 'drac', 'drc', 'ds', 'dsl',
'dtd', 'dts', 'dtsi', 'edf', 'edif', 'edn', 'edo', 'ed', 'edn', 'ecd', 'e',
'E', 'erl', 'hrl', 'yaws', 'elm', 'ec', 'EC', 'strl', 'csc', 'exp', 'fal',
'fan', 'fwt', 'factor', 'fnl', 'wiki', 'fex', 'focexec', 'mas', 'master', 'fs',
'ft', 'fth', 'frt', 'F', 'FOR', 'FPP', 'FTN', 'F77', 'F90', 'F95', 'F03',
'F08', 'f', 'for', 'fortran', 'fpp', 'ftn', 'f77', 'f90', 'f95', 'f03', 'f08',
'fsl', 'mo', 'gdmo', 'ged', 'gift', 'git', 'git', 'git', 'gp', 'gpi', 'go',
'gs', 'gretl', 'gradle', 'groovy', 'gsp', 'haml', 'hsm', 'hs', 'hsc', 'hs',
'hsig', 'lhs', 'chs', 'ht', 'htpp', 'vc', 'ev', 'sum', 'errsum', 'hex', 'h32',
'hws', 't', 'html', 'htm', 'shtml', 'stm', 'erb', 'rhtml', 'html', 'tmpl',
'hb', 'htt', 'htb', 'icn', 'idl', 'idl', 'odl', 'mof', 'pro', 'pro', 'inf',
'INF', 'i', 'ii', 'dat', 'upstream', 'log', 'upstream', 'log', 'log',
'upstreaminstall', 'log', 'usserver', 'log', 'usw2kagt', '4gl', '4gh', 'm4gl',
'ini', 'iss', 'ijs', 'jal', 'JAL', 'jpl', 'jpr', 'java', 'jav', 'jj', 'jjt',
'js', 'javascript', 'es', 'mjs', 'cjs', 'jsx', 'jsp', 'properties',
'properties_', 'properties_', 'clp', 'jgr', 'jov', 'j73', 'jovial', 'json',
'jsonp', 'webmanifest', 'json', 'ipynb', 'kix', 'k', 'kv', 'kt', 'ktm', 'kts',
'ks', 'ace', 'ACE', 'latte', 'lte', 'conf', 'mod', 'sig', 'ldif', 'ld', 'less',
'lex', 'l', 'lxx', 'l', 'll', 'el', 'cl', 'jl', 'lsp', 'lisp', 'el', 'cl', 'L',
'lsp', 'lisp', 'el', 'cl', 'liquid', 'lite', 'lt', 'rc', 'lgt', 'lot', 'lotos',
'lt', 'lou', 'lout', 'lua', 'rockspec', 'lsl', 'lss', 'm4', 'mgp', 'eml', 'mk',
'mak', 'dsp', 'ist', 'mst', 'page', 'man', 'mv', 'mpl', 'mws', 'map',
'markdown', 'mdown', 'mkd', 'mkdn', 'mdwn', 'md', 'mason', 'mhtml', 'comp',
'm', 'nb', 'mel', 'txt', 'hgrc', 'wrap', 'mf', 'mp', 'mgl', 'mix', 'mixal',
'mms', 'mmp', 'mod', 'm2', 'DEF', 'MOD', 'mi', 'isc', 'monk', 'ssc', 'tsc',
'moo', 's19', 's28', 's37', 'mot', 'srec', 'msql', 'mysql', 'rc', 'rc', 'rch',
'mu', 'mush', 'n1ql', 'nql', 'nanorc', 'dat', 'NS', 'ninja', 'ncf', 'ms', 't',
'me', 'tr', 'nr', 'roff', 'tmac', 'mom', 'mm', 'nqc', 'nse', 'nsi', 'nsh',
'ml', 'mli', 'mll', 'mly', 'mlt', 'mlp', 'mlip', 'mli', 'ml', 'occ', 'xom',
'xin', 'opam', 'opam', 'or', 'ora', 'hook', 'papp', 'pxml', 'pxsl', 'p', 'pp',
'inc', 'pas', 'pp', 'dpr', 'lpr', 'fpc', 'pdf', 'pcmk', 'pl', 'PL', 'pl',
'plx', 'al', 'psgi', 'pm', 'pod', 'php', 'php', 'phtml', 'ctp', 'pike', 'pmod',
'cmod', 'rcp', 'pli', 'pl1', 'inp', 'plm', 'p36', 'pac', 'pls', 'plsql', 'plp',
'po', 'pot', 'ps', 'pfa', 'afm', 'eps', 'epsf', 'epsi', 'ai', 'ppd', 'pov',
'inc', 'ps1', 'psd1', 'psm1', 'pssc', 'ps1xml', 'cdxml', 'psc1', 'g', 'g',
'it', 'ih', 'epp', 'obj', 'pc', 'action', 'w', 'i', 'p', 'psf', 'pdb', 'pml',
'psl', 'proto', 'pbtxt', 'pk', 'pyx', 'pxd', 'py', 'pyw', 'ptl', 'pyi', 'rad',
'mat', 'pm6', 'p6', 't6', 'pod6', 'raku', 'rakumod', 'rakudoc', 'rakutest',
'reg', 'rib', 'rego', 'rex', 'orx', 'rxo', 'rxj', 'jrexx', 'rexxj', 'rexx',
'testGroup', 'testUnit', 'rd', 'Rd', 'rd', 'Rnw', 'rnw', 'Snw', 'snw', 'rnw',
'snw', 'Rmd', 'rmd', 'Smd', 'smd', 'rmd', 'smd', 'rss', 'Rrst', 'rrst', 'Srst',
'srst', 'rrst', 'srst', 'r', 'R', 'remind', 'rem', 'rnc', 'rng', 'rpl', 'x',
'rst', 'rtf', 'rb', 'rbw', 'gemspec', 'rbs', 'ru', 'builder', 'rxml', 'rjs',
'rant', 'rake', 'rs', 'sl', 'sas', 'sass', 'sa', 'scala', 'sc', 'sbt', 'sci',
'sce', 'scss', 'sd', 'sdl', 'pr', 'sed', 'svelte', 'siv', 'sieve', 'mc', 'sgm',
'sgml', 'decl', 'dcl', 'dec', 'ebuild', 'bash', 'eclass', 'ksh', 'sh', 'env',
'install', 'tcsh', 'csh', 'zsh', 'scm', 'ss', 'rkt', 'sexp', 'sim', 'sin',
's85', 'sst', 'ssm', 'ssi', '_sst', 'sst', '_sst', 'il', 'ils', 'cdf', 'score',
'st', 'cls', 'tpl', 'smil', 'smi', 'smt', 'smith', 'sno', 'spt', 'mib', 'my',
'hog', 'rules', 'rq', 'sparql', 'spec', 'speedup', 'spdata', 'spd', 'ice',
'sp', 'spice', 'spy', 'spi', 'tyb', 'typ', 'tyc', 'pkb', 'pks', 'sql', 'sqlj',
'sqr', 'sqi', 'conf', 'conf', 'ado', 'do', 'imata', 'mata', 'class', 'class',
'hlp', 'ihlp', 'smcl', 'stp', 'sml', 'cm', 'swift', 'swift', 'sil', 'conf',
'conf', 'conf', 'd', 'conf', 'd', 'conf', 'd', 'd', 'sdc', 'svg', 't', 'tak',
'task', 'tcl', 'tk', 'itcl', 'itk', 'jacl', 'tli', 'slt', 'ttl', 'ti', 'latex',
'sty', 'dtx', 'ltx', 'bbl', 'tex', 'mkii', 'mkiv', 'mkvi', 'mkxl', 'mklx',
'texinfo', 'texi', 'txi', 'tf', 'conf', 'toml', 'tpp', 'treetop', 'tssgm',
'tssop', 'tsscl', 'tutor', 'twig', 'ts', 'tsx', 'uit', 'uil', 'permissions',
'uc', 'conf', 'override', 'conf', 'override', 'conf', 'override', 'conf',
'override', 'vr', 'vri', 'vrh', 'v', 'va', 'vams', 'sv', 'svh', 'hdl', 'vhd',
'vhdl', 'vbe', 'vst', 'vho', 'vim', 'vba', 'hw', 'module', 'pkg', 'bas', 'frm',
'sba', 'wrl', 'vroom', 'vue', 'wast', 'wat', 'wm', 'wml', 'wbt', 'wsml', 'wpl',
'web', 'web', 'ws', 'xhtml', 'xht', 'xpm', 'xpm2', 'conf', 'xs', 'ad', 'msc',
'msf', 'ms', 'xml', 'xmi', 'csproj', 'csproj', 'ui', 'tpm', 'menu', 'wsdl',
'xlf', 'xliff', 'xul', 'xq', 'xql', 'xqm', 'xquery', 'xqy', 'xsd', 'xsl',
'xslt', 'yy', 'yxx', 'y', 'y', 'yaml', 'yml', 'raml', 'zu', 'zut', 'dtml',
'pt', 'cpt', 'zsql', 'z8a', 'conf', 'conf', 'conf', 'conf', 'BUILD', 'hook',
'properties_', 'd', 'rdf', 'vhdl_', 'tmp', 'text', 'txt', 'txt', 'vim', 'lua']

module.exports.extensions = extensions;
